-- Powder Items
weedpowder                 = { name = 'weedpowder', label = 'Weed Powder', weight = 50, type = 'item', image = 'weedpowder.png', unique = false, useable = false, shouldClose = true, description = 'A fine powder made from cannabis leaves.' },
heroinpowder               = { name = 'heroinpowder', label = 'Heroin Powder', weight = 50, type = 'item', image = 'heroinpowder.png', unique = false, useable = false, shouldClose = true, description = 'A fine powder derived from opium poppies.' },
cocainepowder              = { name = 'cocainepowder', label = 'Cocaine Powder', weight = 50, type = 'item', image = 'cocainepowder.png', unique = false, useable = false, shouldClose = true, description = 'A fine white powder derived from coca leaves.' },
-- Leaf Items
cocaleaves                 = { name = 'cocaleaves', label = 'Coca Leaves', weight = 100, type = 'item', image = 'cocaleaves.png', unique = false, useable = false, shouldClose = true, description = 'Leaves of the coca plant, used to make cocaine.' },
weedleaves                 = { name = 'weedleaves', label = 'Weed Leaves', weight = 100, type = 'item', image = 'weedleaves.png', unique = false, useable = false, shouldClose = true, description = 'Raw leaves of the cannabis plant.' },
rawopium                   = { name = 'rawopium', label = 'Raw Opium', weight = 100, type = 'item', image = 'rawopium.png', unique = false, useable = false, shouldClose = true, description = 'Sticky brown substance extracted from poppy pods.' },
-- Pouch Items
cokepouch                  = { name = 'cokepouch', label = 'Coke Pouch', weight = 200, type = 'item', image = 'cokepouch.png', unique = false, useable = false, shouldClose = true, description = 'A small pouch filled with cocaine powder.' },
heroinpouch                = { name = 'heroinpouch', label = 'Heroin Pouch', weight = 200, type = 'item', image = 'heroinpouch.png', unique = false, useable = false, shouldClose = true, description = 'A small pouch filled with heroin powder.' },
weedpouch                  = { name = 'weedpouch', label = 'Weed Pouch', weight = 200, type = 'item', image = 'weedpouch.png', unique = false, useable = false, shouldClose = true, description = 'A small pouch filled with weed powder.' },
plastic_bag                = { name = 'plastic_bag', label = 'Plastic Bag', weight = 50, type = 'item', image = 'plastic_bag.png', unique = false, useable = false, shouldClose = true, description = 'An empty plastic bag for storing items.' },